package com.xxx.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.xxx.bean.UserBean;
import com.xxx.bean.SchoolBean;

import com.xxx.dao.UserBeanDao;
import com.xxx.dao.SchoolBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userBeanDaoConfig;
    private final DaoConfig schoolBeanDaoConfig;

    private final UserBeanDao userBeanDao;
    private final SchoolBeanDao schoolBeanDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userBeanDaoConfig = daoConfigMap.get(UserBeanDao.class).clone();
        userBeanDaoConfig.initIdentityScope(type);

        schoolBeanDaoConfig = daoConfigMap.get(SchoolBeanDao.class).clone();
        schoolBeanDaoConfig.initIdentityScope(type);

        userBeanDao = new UserBeanDao(userBeanDaoConfig, this);
        schoolBeanDao = new SchoolBeanDao(schoolBeanDaoConfig, this);

        registerDao(UserBean.class, userBeanDao);
        registerDao(SchoolBean.class, schoolBeanDao);
    }
    
    public void clear() {
        userBeanDaoConfig.getIdentityScope().clear();
        schoolBeanDaoConfig.getIdentityScope().clear();
    }

    public UserBeanDao getUserBeanDao() {
        return userBeanDao;
    }

    public SchoolBeanDao getSchoolBeanDao() {
        return schoolBeanDao;
    }

}
