package com.xxx.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table user.
 */
public class SchoolBean {

    private String s_id;
    private String name;

    public SchoolBean() {
    }

    public SchoolBean(String s_id) {
        this.s_id = s_id;
    }

    public SchoolBean(String s_id, String name) {
        this.s_id = s_id;
        this.name = name;
    }

    public String getS_id() {
        return s_id;
    }

    public void setS_id(String s_id) {
        this.s_id = s_id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
