package com.xxx.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table user2.
 */
public class UserBean {

    private String id;
    private String phone;
    private String profile_picture;
    private String client_id;
    private String name;
    private String location;
    private String gender;
    private String age;

    public UserBean() {
    }

    public UserBean(String id) {
        this.id = id;
    }

    public UserBean(String id, String phone, String profile_picture, String client_id, String name, String location, String gender, String age) {
        this.id = id;
        this.phone = phone;
        this.profile_picture = profile_picture;
        this.client_id = client_id;
        this.name = name;
        this.location = location;
        this.gender = gender;
        this.age = age;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getProfile_picture() {
        return profile_picture;
    }

    public void setProfile_picture(String profile_picture) {
        this.profile_picture = profile_picture;
    }

    public String getClient_id() {
        return client_id;
    }

    public void setClient_id(String client_id) {
        this.client_id = client_id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getAge() {
        return age;
    }

    public void setAge(String age) {
        this.age = age;
    }

}
